<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AdminMenu;

class AdminMenuSeeder extends Seeder
{
    /**
     * 관리자 메뉴 데이터를 시드합니다.
     */
    public function run(): void
    {
        // 기존 데이터 삭제
        AdminMenu::query()->delete();

        // 현재 DB 데이터로 최신화된 메뉴 구성
        $menus = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => '대시보드',
                'url' => '/backoffice',
                'icon' => 'fa-tachometer-alt',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-01-22 03:55:23',
                'permission_key' => null,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => '시스템 관리',
                'url' => null,
                'icon' => 'fa-cogs',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-01-22 03:55:23',
                'permission_key' => null,
            ],
            [
                'id' => 3,
                'parent_id' => 2,
                'name' => '기본설정',
                'url' => '/backoffice/setting',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-01-22 04:00:20',
                'permission_key' => null,
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'name' => '메뉴 관리',
                'url' => '/backoffice/admin-menus',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-09 14:41:00',
                'permission_key' => null,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => '기본설정',
                'url' => null,
                'icon' => 'fa-file-alt',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-01-22 03:55:23',
                'permission_key' => null,
            ],
            [
                'id' => 7,
                'parent_id' => 2,
                'name' => '게시판 관리',
                'url' => '/backoffice/boards',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-09 14:41:06',
                'permission_key' => null,
            ],
            [
                'id' => 8,
                'parent_id' => 21,
                'name' => '팝업 관리',
                'url' => '/backoffice/popups',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-01-22 04:07:02',
                'permission_key' => null,
            ],
            [
                'id' => 9,
                'parent_id' => 2,
                'name' => '게시판 템플릿 관리',
                'url' => '/backoffice/board-templates',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-06 09:58:14',
                'updated_at' => '2025-10-19 14:11:43',
                'permission_key' => null,
            ],
            [
                'id' => 10,
                'parent_id' => 19,
                'name' => '공지사항',
                'url' => '/backoffice/board-posts/notices',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-06 12:44:51',
                'updated_at' => '2026-01-22 04:02:19',
                'permission_key' => null,
            ],
            [
                'id' => 17,
                'parent_id' => 19,
                'name' => '자료실',
                'url' => '/backoffice/board-posts/library',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-08-21 07:20:49',
                'updated_at' => '2026-01-22 04:04:54',
                'permission_key' => null,
            ],
            [
                'id' => 18,
                'parent_id' => 21,
                'name' => '메인 배너 관리',
                'url' => '/backoffice/banners',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-08-24 09:35:23',
                'updated_at' => '2026-01-22 04:07:02',
                'permission_key' => null,
            ],
            [
                'id' => 19,
                'parent_id' => null,
                'name' => '게시판관리',
                'url' => null,
                'icon' => 'fa-chart-bar',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-08-24 09:36:13',
                'updated_at' => '2025-12-18 08:46:23',
                'permission_key' => null,
            ],
            [
                'id' => 20,
                'parent_id' => 6,
                'name' => '관리자 관리',
                'url' => '/backoffice/admins',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-19 00:19:49',
                'updated_at' => '2025-10-09 04:28:31',
                'permission_key' => null,
            ],
            [
                'id' => 21,
                'parent_id' => null,
                'name' => '홈페이지관리',
                'url' => null,
                'icon' => 'fa-home',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:20:08',
                'updated_at' => '2025-12-18 08:46:23',
                'permission_key' => null,
            ],
            [
                'id' => 23,
                'parent_id' => 6,
                'name' => '권한 관리',
                'url' => '/backoffice/admin-groups',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-10-18 01:55:21',
                'updated_at' => '2026-01-22 04:08:28',
                'permission_key' => null,
            ],
            [
                'id' => 39,
                'parent_id' => 6,
                'name' => '코드 관리',
                'url' => '/backoffice/categories',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-10-09 01:02:41',
                'updated_at' => '2026-01-22 04:00:31',
                'permission_key' => null,
            ],
            [
                'id' => 40,
                'parent_id' => 19,
                'name' => 'FAQ',
                'url' => '/backoffice/board-posts/faq',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-10-26 14:20:31',
                'updated_at' => '2026-01-22 04:05:13',
                'permission_key' => null,
            ],
            [
                'id' => 41,
                'parent_id' => null,
                'name' => '통계 관리',
                'url' => null,
                'icon' => 'fa-chart-line',
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:44:54',
                'updated_at' => '2025-12-18 08:45:42',
                'permission_key' => null,
            ],
            [
                'id' => 42,
                'parent_id' => 41,
                'name' => '접속통계',
                'url' => '/backoffice/access-statistics',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:46:17',
                'updated_at' => '2025-12-18 08:46:27',
                'permission_key' => null,
            ],
            [
                'id' => 43,
                'parent_id' => 41,
                'name' => '사용자 접속로그 목록',
                'url' => '/backoffice/user-access-logs',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:46:51',
                'updated_at' => '2025-12-18 08:47:27',
                'permission_key' => null,
            ],
            [
                'id' => 44,
                'parent_id' => 41,
                'name' => '관리자 접속로그 목록',
                'url' => '/backoffice/admin-access-logs',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:47:05',
                'updated_at' => '2025-12-18 08:47:27',
                'permission_key' => null,
            ],
            [
                'id' => 45,
                'parent_id' => 21,
                'name' => '조직도 관리',
                'url' => '/backoffice/organizational',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-01-22 03:45:23',
                'updated_at' => '2026-01-22 04:07:02',
                'permission_key' => null,
            ],
            [
                'id' => 46,
                'parent_id' => 21,
                'name' => '연혁 관리',
                'url' => '/backoffice/history',
                'icon' => null,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2026-01-22 03:45:23',
                'updated_at' => '2026-01-22 04:07:02',
                'permission_key' => null,
            ],
            [
                'id' => 47,
                'parent_id' => null,
                'name' => '회원관리',
                'url' => null,
                'icon' => 'fa-users',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-01-22 03:45:23',
                'updated_at' => '2026-01-22 03:55:23',
                'permission_key' => null,
            ],
            [
                'id' => 48,
                'parent_id' => 47,
                'name' => '회원 목록',
                'url' => '/backoffice/members',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-01-22 03:45:23',
                'updated_at' => '2026-01-22 04:08:40',
                'permission_key' => null,
            ],
            [
                'id' => 49,
                'parent_id' => 47,
                'name' => '학교(회원교)관리',
                'url' => '/backoffice/schools',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-01-22 12:00:00',
                'updated_at' => '2026-01-22 12:00:00',
                'permission_key' => null,
            ],
            [
                'id' => 51,
                'parent_id' => 47,
                'name' => '회원 문의(리스트)',
                'url' => '/backoffice/inquiries',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-01-22 13:00:00',
                'updated_at' => '2026-01-22 13:00:00',
                'permission_key' => null,
            ],
            [
                'id' => 50,
                'parent_id' => 19,
                'name' => '회원사 채용정보',
                'url' => '/backoffice/board-posts/recruitments',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-01-22 04:05:38',
                'updated_at' => '2026-01-22 04:05:41',
                'permission_key' => null,
            ],
            [
                'id' => 52,
                'parent_id' => 21,
                'name' => '정관 관리',
                'url' => '/backoffice/board-posts/bylaws',
                'icon' => null,
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2026-01-22 04:06:59',
                'updated_at' => '2026-01-22 04:07:02',
                'permission_key' => null,
            ],
            [
                'id' => 53,
                'parent_id' => 21,
                'name' => '교육 안내 관리',
                'url' => '/backoffice/education',
                'icon' => null,
                'order' => 7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 54,
                'parent_id' => null,
                'name' => '교육 관리',
                'url' => null,
                'icon' => 'fa-graduation-cap',
                'order' => 7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 55,
                'parent_id' => 54,
                'name' => '교육 목록',
                'url' => '/backoffice/education-programs',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 56,
                'parent_id' => 54,
                'name' => '온라인 교육 목록',
                'url' => '/backoffice/online-educations',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
        ];

        // parent_id가 null인 메뉴들을 먼저 생성
        $parentMenus = array_filter($menus, function($menu) {
            return $menu['parent_id'] === null;
        });
        
        foreach ($parentMenus as $menu) {
            AdminMenu::create($menu);
        }
        
        // 그 다음에 자식 메뉴들을 생성
        $childMenus = array_filter($menus, function($menu) {
            return $menu['parent_id'] !== null;
        });
        
        foreach ($childMenus as $menu) {
            AdminMenu::create($menu);
        }
    }
}
