<?php

namespace Database\Seeders;

use App\Models\EducationProgram;
use App\Models\EducationSchedule;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EducationProgramSeeder extends Seeder
{
    /**
     * 교육 프로그램 시드 데이터를 등록합니다.
     */
    public function run(): void
    {
        EducationSchedule::query()->delete();
        EducationProgram::query()->delete();

        $programs = [
            [
                'education_type' => '정기교육',
                'education_class' => '6차',
                'is_public' => true,
                'application_status' => '접수중',
                'name' => '2025년 산학협력단 직원 전문성 강화 교육(기본과정)',
                'period_start' => Carbon::parse('2025-12-03'),
                'period_end' => Carbon::parse('2025-12-05'),
                'period_time' => '총 15시간',
                'is_accommodation' => true,
                'location' => '서울대학교 연구공원 943동 1층 세미나실',
                'target' => '산학협력단 및 사업단·센터 실무 연구관리자(입사 5년 이내)',
                'content' => '<p>산학협력단 소속 직원의 역량 강화를 위한 체계적이고 현장 중심적인 연구관리 및 산학협력 직무교육입니다.</p>',
                'completion_criteria' => '교육이수율 90% 이상 + 설문조사 제출 시 수료증 발급',
                'certificate_type' => '수료증',
                'completion_hours' => 15,
                'application_start' => Carbon::parse('2025-11-04 09:00:00'),
                'application_end' => Carbon::parse('2025-11-28 18:00:00'),
                'capacity' => 40,
                'capacity_unlimited' => false,
                'payment_methods' => ['무통장입금', '온라인카드결제'],
                'deposit_account' => "농협은행 301-0334-8275-91 (전국대학연구산학협력관리자협의회)\n입금자명: 소속기관명 + 성명",
                'deposit_deadline_days' => 3,
                'fee_member_twin' => 570000,
                'fee_member_single' => 680000,
                'fee_member_no_stay' => 360000,
                'fee_guest_twin' => 670000,
                'fee_guest_single' => 780000,
                'fee_guest_no_stay' => 460000,
                'refund_twin_fee' => 130000,
                'refund_single_fee' => 260000,
                'refund_no_stay_fee' => 75000,
                'refund_twin_deadline' => '교육 시작일 기준 30일 전까지',
                'refund_single_deadline' => '교육 시작일 기준 30일 전까지',
                'refund_no_stay_deadline' => '교육 시작일 기준 1주일 전까지',
                'refund_same_day_fee' => 300000,
            ],
            [
                'education_type' => '수시교육',
                'education_class' => null,
                'is_public' => true,
                'application_status' => '접수마감',
                'name' => '2025년 연구현장 소통 콘서트 연구관리자를 위한 연구비 교육',
                'period_start' => Carbon::parse('2025-10-22'),
                'period_end' => Carbon::parse('2025-10-22'),
                'period_time' => '14:00~16:00',
                'is_accommodation' => false,
                'location' => '동국대학교(서울캠퍼스) 본관 3층 남산홀',
                'target' => '재단 지원과제 수행기관 연구관리자',
                'content' => '<p>연구현장 소통 강화를 위한 연구비 교육 프로그램입니다.</p>',
                'completion_criteria' => '교육 이수율 90% 이상',
                'certificate_type' => '이수증',
                'completion_hours' => 2,
                'application_start' => Carbon::parse('2025-10-14 09:00:00'),
                'application_end' => Carbon::parse('2025-10-17 18:00:00'),
                'capacity' => 40,
                'capacity_unlimited' => false,
                'payment_methods' => ['무통장입금'],
                'deposit_account' => '농협은행 301-0334-8275-91',
                'deposit_deadline_days' => 3,
                'fee_member_twin' => null,
                'fee_member_single' => null,
                'fee_member_no_stay' => null,
                'fee_guest_twin' => null,
                'fee_guest_single' => null,
                'fee_guest_no_stay' => null,
                'refund_twin_fee' => null,
                'refund_single_fee' => null,
                'refund_no_stay_fee' => null,
                'refund_twin_deadline' => null,
                'refund_single_deadline' => null,
                'refund_no_stay_deadline' => null,
                'refund_same_day_fee' => null,
            ],
            [
                'education_type' => '자격증',
                'education_class' => null,
                'is_public' => true,
                'application_status' => '접수예정',
                'name' => '대학연구행정전문가 자격시험(2급)',
                'period_start' => Carbon::parse('2026-12-07'),
                'period_end' => Carbon::parse('2026-12-07'),
                'period_time' => null,
                'is_accommodation' => false,
                'location' => null,
                'target' => '대학·정부출연연구기관·산학협력단 등에서 연구행정 또는 연구관리 업무를 수행 중인 실무자',
                'content' => '<p>대학연구행정전문가 2급 자격시험 안내입니다.</p>',
                'completion_criteria' => null,
                'certificate_type' => '수료증',
                'completion_hours' => null,
                'application_start' => Carbon::parse('2026-11-18 09:00:00'),
                'application_end' => Carbon::parse('2026-11-29 18:00:00'),
                'capacity' => null,
                'capacity_unlimited' => true,
                'payment_methods' => ['무통장입금', '온라인카드결제'],
                'deposit_account' => '농협은행 301-0334-8275-91',
                'deposit_deadline_days' => 3,
                'fee_member_twin' => null,
                'fee_member_single' => null,
                'fee_member_no_stay' => null,
                'fee_guest_twin' => null,
                'fee_guest_single' => null,
                'fee_guest_no_stay' => null,
                'refund_twin_fee' => null,
                'refund_single_fee' => null,
                'refund_no_stay_fee' => null,
                'refund_twin_deadline' => null,
                'refund_single_deadline' => null,
                'refund_no_stay_deadline' => null,
                'refund_same_day_fee' => null,
            ],
            [
                'education_type' => '온라인교육',
                'education_class' => '5차시(인정시간: 5시간)',
                'is_public' => true,
                'application_status' => '접수마감',
                'name' => '산학협력단 연구행정 기초과정(E-learning)',
                'period_start' => Carbon::parse('2025-01-01'),
                'period_end' => Carbon::parse('2025-12-31'),
                'period_time' => '온라인 학습',
                'is_accommodation' => false,
                'location' => '온라인 학습',
                'target' => '산학협력단 신규직원 및 연구행정 입문자',
                'content' => '<p>온라인 기반 연구행정 기초과정입니다.</p>',
                'completion_criteria' => '영상 시청 100% + 퀴즈 통과',
                'certificate_type' => '이수증',
                'completion_hours' => 5,
                'application_start' => Carbon::parse('2025-10-14 09:00:00'),
                'application_end' => Carbon::parse('2025-10-17 18:00:00'),
                'capacity' => null,
                'capacity_unlimited' => true,
                'payment_methods' => ['온라인카드결제'],
                'deposit_account' => null,
                'deposit_deadline_days' => null,
                'fee_member_twin' => null,
                'fee_member_single' => null,
                'fee_member_no_stay' => null,
                'fee_guest_twin' => null,
                'fee_guest_single' => null,
                'fee_guest_no_stay' => null,
                'refund_twin_fee' => null,
                'refund_single_fee' => null,
                'refund_no_stay_fee' => null,
                'refund_twin_deadline' => null,
                'refund_single_deadline' => null,
                'refund_no_stay_deadline' => null,
                'refund_same_day_fee' => null,
            ],
        ];

        foreach ($programs as $data) {
            $program = EducationProgram::create($data);

            if ($program->education_type === '정기교육' && $program->education_class) {
                EducationSchedule::create([
                    'education_program_id' => $program->id,
                    'class_name' => $program->education_class,
                    'schedule_start' => $program->period_start,
                    'schedule_end' => $program->period_end,
                    'location' => $program->location,
                    'capacity' => $program->capacity ? $program->capacity . '명' : null,
                    'note' => '숙박교육(희망자)',
                ]);
            }
        }
    }
}
